version: '2'
distribution_spec:
  description: Red Hat distribution of Llama Stack
  providers:
    inference:
    - remote::vllm
    - inline::sentence-transformers
    vector_io:
    - inline::milvus
    safety:
    - remote::trustyai_fms
    agents:
    - inline::meta-reference
    eval:
    - remote::trustyai_lmeval
    datasetio:
    - remote::huggingface
    - inline::localfs
    scoring:
    - inline::basic
    - inline::llm-as-judge
    - inline::braintrust
    telemetry:
    - inline::meta-reference
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::rag-runtime
    - remote::model-context-protocol
  container_image: quay.io/aipcc/base-images/cpu:2.0-1749153990
additional_pip_packages:
- aiosqlite
- sqlalchemy[asyncio]
image_type: container
image_name: llama-stack-rh
external_providers_dir: redhat-distribution/providers.d
